# AppVeyor.com is a Continuous Integration service to build and run tests under Windows

build: off

environment:
  matrix:
    - PYTHON: 2.7
      MINICONDA: C:\Miniconda
      PYTHON_ARCH: 32

    - PYTHON: 3.5
      MINICONDA: C:\Miniconda35
      PYTHON_ARCH: 32

    - PYTHON: 3.6
      MINICONDA: C:\Miniconda3
      PYTHON_ARCH: 32

    - PYTHON: 2.7
      MINICONDA: C:\Miniconda-x64
      PYTHON_ARCH: 64

    - PYTHON: 3.5
      MINICONDA: C:\Miniconda35-x64
      PYTHON_ARCH: 64

    - PYTHON: 3.6
      MINICONDA: C:\Miniconda3-x64
      PYTHON_ARCH: 64

init:
  - "ECHO %PYTHON% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON% numpy scipy matplotlib cython"
  - activate test-environment
  - python --version
  #- pip install discretize
  - python setup.py build_ext --inplace
