# AppVeyor.com is a Continuous Integration service to build and run tests under Windows

build: off


environment:
  global:
    CMD_IN_ENV: 'cmd /E:ON /V:ON /C .\run_with_env.cmd'

  matrix:
    - PYTHON_VERSION: 2.7
      CONDA: C:\Miniconda

    - PYTHON_VERSION: 3.5
      CONDA: C:\Miniconda35

    - PYTHON_VERSION: 3.6
      CONDA: C:\Miniconda36

image: Visual Studio 2015

platform:
- x86
- x64

init:
  - ps: if ($Env:PLATFORM -eq "x64") { $Env:CONDA = "${Env:CONDA}-x64" }
  - ps: Write-Host $Env:PYTHON_VERSION
  - ps: Write-Host $Env:CONDA
  - ps: Write-Host $Env:PLATFORM

install:
  # Load the conda root environment, configure and install some packages
  - '"%CONDA%\Scripts\activate.bat"'
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install numpy scipy matplotlib cython
  # Show conda info for debugging
  - conda info -a

  - python --version
  #- pip install discretize
  - python setup.py build_ext --inplace
