# AppVeyor.com is a Continuous Integration service to build and run tests under Windows

build: off


environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script interpreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_ENV: "cmd /E:ON /V:ON /C run_with_env.cmd"

  matrix:
    - PYTHON_VERSION: 2.7
      CONDA: C:\Miniconda

    #- PYTHON_VERSION: 3.5
    #  CONDA: C:\Miniconda35

    #- PYTHON_VERSION: 3.6
    #  CONDA: C:\Miniconda36

image: Visual Studio 2015

platform:
#- x86
- x64

init:
  - ps: if ($Env:PLATFORM -eq "x64") { $Env:CONDA = "${Env:CONDA}-x64" }
  - ps: Write-Host $Env:PYTHON_VERSION
  - ps: Write-Host $Env:CONDA
  - ps: Write-Host $Env:PLATFORM
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


install:
  # Load the conda root environment, configure and install some packages
  - '"%CONDA%\Scripts\activate.bat"'
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install numpy scipy matplotlib cython
  # Show conda info for debugging
  - conda info -a

  - python --version
  #- pip install discretize
  - python setup.py build_ext --inplace

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
